// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIrLgaCuC5a_DLyIlIpTuA06sbXbrZMEE',
    appId: '1:712531455621:web:39a43e99d0706d04c203ec',
    messagingSenderId: '712531455621',
    projectId: 'chatty-cd20e',
    authDomain: 'chatty-cd20e.firebaseapp.com',
    storageBucket: 'chatty-cd20e.appspot.com',
    measurementId: 'G-5D31SBD3ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbHY66MeN9XS3-a3x6bwKoyNKIA_Kzbcw',
    appId: '1:712531455621:android:8a12e9c52f41f8bbc203ec',
    messagingSenderId: '712531455621',
    projectId: 'chatty-cd20e',
    storageBucket: 'chatty-cd20e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy3Qd4eLTp3Ew6AJGPVJt_vv7oODCzNI4',
    appId: '1:712531455621:ios:64261ad0c515da6dc203ec',
    messagingSenderId: '712531455621',
    projectId: 'chatty-cd20e',
    storageBucket: 'chatty-cd20e.appspot.com',
    iosClientId: '712531455621-18oo91qcs75vpvhklp9ktghtucoe4m0d.apps.googleusercontent.com',
    iosBundleId: 'idiot.geeks.chatRoom',
  );
}
